sudo: required

language: csharp

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
- docker pull microsoft/aspnetcore:2.0.0
- docker pull microsoft/aspnetcore-build:2.0.0
- cat Dockerfile | envsubst | docker build -t local/app .

script:
- docker login --username=_ --password="$DOCKER_PASSWORD" registry.heroku.com
- docker tag local/app:latest registry.heroku.com/pggameapplication/web
- docker push registry.heroku.com/pggameapplication/web