sudo: required

language: csharp

services:
  - docker

before_install:
- cd GameApplication
- docker pull microsoft/aspnetcore:2.0.0
- docker pull microsoft/aspnetcore-build:2.0.0
- docker build -t local/app .
