sudo: required

language: csharp

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
- docker pull microsoft/aspnetcore:2.0.0
- docker pull microsoft/aspnetcore-build:2.0.0
- docker build -t local/app .
